name: DocFX

on:
  workflow_dispatch:
  push:
    branches: ["main"]

# GitHub Pagesにデプロイするための権限設定
permissions:
  contents: read
  pages: write
  id-token: write

# 同時実行制御（GitHub Pagesデプロイの重複を防ぐ）
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup DocFX
        shell: bash
        run: |
          dotnet tool install -g docfx
          docfx docfx/docfx.json

      # GitHub Pages用のアーティファクトとしてアップロード
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docfx/_site

  deploy:
    needs: build
    runs-on: ubuntu-latest 
    timeout-minutes: 5
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      # GitHub Pages用のデプロイアクション
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
