name: DocFX

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup DocFX
        shell: bash
        run: |
          dotnet tool install -g docfx
          docfx docfx/docfx.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dotnet_docs
          path: docfx/_site

  deploy:
    needs: build
    runs-on: ubuntu-latest 
    timeout-minutes: 5
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dotnet_docs
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
