name: DocFX

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - 'docfx/**'           # DocFX設定変更時
      - 'Assets/**/*.cs'     # C#スクリプト変更時
      - '*.md'               # README等のドキュメント変更時
      - 'docs/**'            # docsフォルダ変更時

# GitHub Pagesにデプロイするための権限設定
permissions:
  contents: write  # gh-pagesブランチへの書き込み権限
  pages: write
  id-token: write

# 同時実行制御（GitHub Pagesデプロイの重複を防ぐ）
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup DocFX
        shell: bash
        run: |
          dotnet tool install -g docfx
          docfx docfx/docfx.json

      # 通常のアーティファクトとしてアップロード
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docfx_output
          path: docfx/_site

  deploy:
    needs: build
    runs-on: ubuntu-latest 
    timeout-minutes: 5
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: docfx_output
          path: ./docs_site
          
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs_site
          publish_branch: gh-pages
